### PR TITLE
Ability to run liquibase changelog in context of non-default (i.e. PUBLIC) schema

### PR DESCRIPTION
**Pull request by tmszdmsk**

### CODE REVIEW

**Comment by tmszdmsk** [comment]
no problem @zapodot! Do you plan to release it anytime soon?

**Comment by zapodot** [comment]
ASAP. It should be available in a few days :-)

**Comment by zapodot** [comment]
You now what? Just released version 0.7 to Maven central. Expect to wait a
few hours before it is widely available :-)

Thanks again for your contribution!

**Comment by tmszdmsk** [comment]
Great! (to be honest I spotted it in sonatype oss on Monday ;)

**Pull request merged**
